name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install wasm-pack
        run: |
          npm install -g wasm-pack
      - name: Run rust checks
        run: |
          cargo clippy -- -D warnings
          cargo fmt --check
      - name: Build JS lib
        run: |
          npm install
          npm run prepare-package
      - name: Run JS tests
        run: |
          cd js-tests
          npm install
          npm test
      - name: Run node JS example
        run: |
          cd examples/node
          npm install
          npm start
      - name: Build frontend JS example
        run: |
          cd examples/frontend
          npm install
          npm run build
